Tweak error messages

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -105,7 +105,7 @@ install_buildpack () {
 		cd "${BUILDPACK_DIR}" &&
 		git log -n 1 --pretty='format:%h'
 	); then
-		echo 'error' >&2
+		echo ' error' >&2
 		return 1
 	fi
 	echo " done, ${commit_hash:0:7}" >&2
